package com.huawei.apw.demo.batch.beans;

import java.io.Serializable;
import java.util.Date;

public class SupplierInvoice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_company
     *
     * @mbggenerated
     */
    private String supplierCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_site
     *
     * @mbggenerated
     */
    private String supplierSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_bank_code
     *
     * @mbggenerated
     */
    private String supplierBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_bank_name
     *
     * @mbggenerated
     */
    private String supplierBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_extend_1
     *
     * @mbggenerated
     */
    private String supplierExtend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_extend_2
     *
     * @mbggenerated
     */
    private String supplierExtend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_extend_3
     *
     * @mbggenerated
     */
    private String supplierExtend3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_extend_4
     *
     * @mbggenerated
     */
    private String supplierExtend4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.supplier_extend_5
     *
     * @mbggenerated
     */
    private String supplierExtend5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_number
     *
     * @mbggenerated
     */
    private String poNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_company
     *
     * @mbggenerated
     */
    private String poCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_department
     *
     * @mbggenerated
     */
    private String poDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_prepayment_po_number
     *
     * @mbggenerated
     */
    private String poPrepaymentPoNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_1
     *
     * @mbggenerated
     */
    private String poExtend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_2
     *
     * @mbggenerated
     */
    private String poExtend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_3
     *
     * @mbggenerated
     */
    private String poExtend3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_4
     *
     * @mbggenerated
     */
    private String poExtend4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_5
     *
     * @mbggenerated
     */
    private String poExtend5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_6
     *
     * @mbggenerated
     */
    private String poExtend6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_7
     *
     * @mbggenerated
     */
    private String poExtend7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_8
     *
     * @mbggenerated
     */
    private String poExtend8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.po_extend_9
     *
     * @mbggenerated
     */
    private String poExtend9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_number
     *
     * @mbggenerated
     */
    private String invoiceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_type
     *
     * @mbggenerated
     */
    private String invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_amount
     *
     * @mbggenerated
     */
    private Double invoiceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoide_date_received
     *
     * @mbggenerated
     */
    private Date invoideDateReceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_date_expense
     *
     * @mbggenerated
     */
    private Date invoiceDateExpense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_date_expense_start
     *
     * @mbggenerated
     */
    private Date invoiceDateExpenseStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_date_expense_period
     *
     * @mbggenerated
     */
    private Date invoiceDateExpensePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_expense_type
     *
     * @mbggenerated
     */
    private String invoiceExpenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_fin_location
     *
     * @mbggenerated
     */
    private String invoiceFinLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_fin_currency
     *
     * @mbggenerated
     */
    private String invoiceFinCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_fin_currency_payment
     *
     * @mbggenerated
     */
    private String invoiceFinCurrencyPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_1
     *
     * @mbggenerated
     */
    private String invoiceBasic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_2
     *
     * @mbggenerated
     */
    private String invoiceBasic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_3
     *
     * @mbggenerated
     */
    private String invoiceBasic3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_4
     *
     * @mbggenerated
     */
    private String invoiceBasic4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_5
     *
     * @mbggenerated
     */
    private String invoiceBasic5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_6
     *
     * @mbggenerated
     */
    private String invoiceBasic6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_7
     *
     * @mbggenerated
     */
    private String invoiceBasic7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_8
     *
     * @mbggenerated
     */
    private String invoiceBasic8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_invoice.invoice_basic_9
     *
     * @mbggenerated
     */
    private String invoiceBasic9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_invoice
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.id
     *
     * @return the value of supplier_invoice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.id
     *
     * @param id the value for supplier_invoice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_company
     *
     * @return the value of supplier_invoice.supplier_company
     *
     * @mbggenerated
     */
    public String getSupplierCompany() {
        return supplierCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_company
     *
     * @param supplierCompany the value for supplier_invoice.supplier_company
     *
     * @mbggenerated
     */
    public void setSupplierCompany(String supplierCompany) {
        this.supplierCompany = supplierCompany == null ? null : supplierCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_site
     *
     * @return the value of supplier_invoice.supplier_site
     *
     * @mbggenerated
     */
    public String getSupplierSite() {
        return supplierSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_site
     *
     * @param supplierSite the value for supplier_invoice.supplier_site
     *
     * @mbggenerated
     */
    public void setSupplierSite(String supplierSite) {
        this.supplierSite = supplierSite == null ? null : supplierSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_bank_code
     *
     * @return the value of supplier_invoice.supplier_bank_code
     *
     * @mbggenerated
     */
    public String getSupplierBankCode() {
        return supplierBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_bank_code
     *
     * @param supplierBankCode the value for supplier_invoice.supplier_bank_code
     *
     * @mbggenerated
     */
    public void setSupplierBankCode(String supplierBankCode) {
        this.supplierBankCode = supplierBankCode == null ? null : supplierBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_bank_name
     *
     * @return the value of supplier_invoice.supplier_bank_name
     *
     * @mbggenerated
     */
    public String getSupplierBankName() {
        return supplierBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_bank_name
     *
     * @param supplierBankName the value for supplier_invoice.supplier_bank_name
     *
     * @mbggenerated
     */
    public void setSupplierBankName(String supplierBankName) {
        this.supplierBankName = supplierBankName == null ? null : supplierBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_extend_1
     *
     * @return the value of supplier_invoice.supplier_extend_1
     *
     * @mbggenerated
     */
    public String getSupplierExtend1() {
        return supplierExtend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_extend_1
     *
     * @param supplierExtend1 the value for supplier_invoice.supplier_extend_1
     *
     * @mbggenerated
     */
    public void setSupplierExtend1(String supplierExtend1) {
        this.supplierExtend1 = supplierExtend1 == null ? null : supplierExtend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_extend_2
     *
     * @return the value of supplier_invoice.supplier_extend_2
     *
     * @mbggenerated
     */
    public String getSupplierExtend2() {
        return supplierExtend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_extend_2
     *
     * @param supplierExtend2 the value for supplier_invoice.supplier_extend_2
     *
     * @mbggenerated
     */
    public void setSupplierExtend2(String supplierExtend2) {
        this.supplierExtend2 = supplierExtend2 == null ? null : supplierExtend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_extend_3
     *
     * @return the value of supplier_invoice.supplier_extend_3
     *
     * @mbggenerated
     */
    public String getSupplierExtend3() {
        return supplierExtend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_extend_3
     *
     * @param supplierExtend3 the value for supplier_invoice.supplier_extend_3
     *
     * @mbggenerated
     */
    public void setSupplierExtend3(String supplierExtend3) {
        this.supplierExtend3 = supplierExtend3 == null ? null : supplierExtend3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_extend_4
     *
     * @return the value of supplier_invoice.supplier_extend_4
     *
     * @mbggenerated
     */
    public String getSupplierExtend4() {
        return supplierExtend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_extend_4
     *
     * @param supplierExtend4 the value for supplier_invoice.supplier_extend_4
     *
     * @mbggenerated
     */
    public void setSupplierExtend4(String supplierExtend4) {
        this.supplierExtend4 = supplierExtend4 == null ? null : supplierExtend4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.supplier_extend_5
     *
     * @return the value of supplier_invoice.supplier_extend_5
     *
     * @mbggenerated
     */
    public String getSupplierExtend5() {
        return supplierExtend5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.supplier_extend_5
     *
     * @param supplierExtend5 the value for supplier_invoice.supplier_extend_5
     *
     * @mbggenerated
     */
    public void setSupplierExtend5(String supplierExtend5) {
        this.supplierExtend5 = supplierExtend5 == null ? null : supplierExtend5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_number
     *
     * @return the value of supplier_invoice.po_number
     *
     * @mbggenerated
     */
    public String getPoNumber() {
        return poNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_number
     *
     * @param poNumber the value for supplier_invoice.po_number
     *
     * @mbggenerated
     */
    public void setPoNumber(String poNumber) {
        this.poNumber = poNumber == null ? null : poNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_company
     *
     * @return the value of supplier_invoice.po_company
     *
     * @mbggenerated
     */
    public String getPoCompany() {
        return poCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_company
     *
     * @param poCompany the value for supplier_invoice.po_company
     *
     * @mbggenerated
     */
    public void setPoCompany(String poCompany) {
        this.poCompany = poCompany == null ? null : poCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_department
     *
     * @return the value of supplier_invoice.po_department
     *
     * @mbggenerated
     */
    public String getPoDepartment() {
        return poDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_department
     *
     * @param poDepartment the value for supplier_invoice.po_department
     *
     * @mbggenerated
     */
    public void setPoDepartment(String poDepartment) {
        this.poDepartment = poDepartment == null ? null : poDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_prepayment_po_number
     *
     * @return the value of supplier_invoice.po_prepayment_po_number
     *
     * @mbggenerated
     */
    public String getPoPrepaymentPoNumber() {
        return poPrepaymentPoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_prepayment_po_number
     *
     * @param poPrepaymentPoNumber the value for supplier_invoice.po_prepayment_po_number
     *
     * @mbggenerated
     */
    public void setPoPrepaymentPoNumber(String poPrepaymentPoNumber) {
        this.poPrepaymentPoNumber = poPrepaymentPoNumber == null ? null : poPrepaymentPoNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_1
     *
     * @return the value of supplier_invoice.po_extend_1
     *
     * @mbggenerated
     */
    public String getPoExtend1() {
        return poExtend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_1
     *
     * @param poExtend1 the value for supplier_invoice.po_extend_1
     *
     * @mbggenerated
     */
    public void setPoExtend1(String poExtend1) {
        this.poExtend1 = poExtend1 == null ? null : poExtend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_2
     *
     * @return the value of supplier_invoice.po_extend_2
     *
     * @mbggenerated
     */
    public String getPoExtend2() {
        return poExtend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_2
     *
     * @param poExtend2 the value for supplier_invoice.po_extend_2
     *
     * @mbggenerated
     */
    public void setPoExtend2(String poExtend2) {
        this.poExtend2 = poExtend2 == null ? null : poExtend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_3
     *
     * @return the value of supplier_invoice.po_extend_3
     *
     * @mbggenerated
     */
    public String getPoExtend3() {
        return poExtend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_3
     *
     * @param poExtend3 the value for supplier_invoice.po_extend_3
     *
     * @mbggenerated
     */
    public void setPoExtend3(String poExtend3) {
        this.poExtend3 = poExtend3 == null ? null : poExtend3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_4
     *
     * @return the value of supplier_invoice.po_extend_4
     *
     * @mbggenerated
     */
    public String getPoExtend4() {
        return poExtend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_4
     *
     * @param poExtend4 the value for supplier_invoice.po_extend_4
     *
     * @mbggenerated
     */
    public void setPoExtend4(String poExtend4) {
        this.poExtend4 = poExtend4 == null ? null : poExtend4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_5
     *
     * @return the value of supplier_invoice.po_extend_5
     *
     * @mbggenerated
     */
    public String getPoExtend5() {
        return poExtend5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_5
     *
     * @param poExtend5 the value for supplier_invoice.po_extend_5
     *
     * @mbggenerated
     */
    public void setPoExtend5(String poExtend5) {
        this.poExtend5 = poExtend5 == null ? null : poExtend5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_6
     *
     * @return the value of supplier_invoice.po_extend_6
     *
     * @mbggenerated
     */
    public String getPoExtend6() {
        return poExtend6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_6
     *
     * @param poExtend6 the value for supplier_invoice.po_extend_6
     *
     * @mbggenerated
     */
    public void setPoExtend6(String poExtend6) {
        this.poExtend6 = poExtend6 == null ? null : poExtend6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_7
     *
     * @return the value of supplier_invoice.po_extend_7
     *
     * @mbggenerated
     */
    public String getPoExtend7() {
        return poExtend7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_7
     *
     * @param poExtend7 the value for supplier_invoice.po_extend_7
     *
     * @mbggenerated
     */
    public void setPoExtend7(String poExtend7) {
        this.poExtend7 = poExtend7 == null ? null : poExtend7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_8
     *
     * @return the value of supplier_invoice.po_extend_8
     *
     * @mbggenerated
     */
    public String getPoExtend8() {
        return poExtend8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_8
     *
     * @param poExtend8 the value for supplier_invoice.po_extend_8
     *
     * @mbggenerated
     */
    public void setPoExtend8(String poExtend8) {
        this.poExtend8 = poExtend8 == null ? null : poExtend8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.po_extend_9
     *
     * @return the value of supplier_invoice.po_extend_9
     *
     * @mbggenerated
     */
    public String getPoExtend9() {
        return poExtend9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.po_extend_9
     *
     * @param poExtend9 the value for supplier_invoice.po_extend_9
     *
     * @mbggenerated
     */
    public void setPoExtend9(String poExtend9) {
        this.poExtend9 = poExtend9 == null ? null : poExtend9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_number
     *
     * @return the value of supplier_invoice.invoice_number
     *
     * @mbggenerated
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_number
     *
     * @param invoiceNumber the value for supplier_invoice.invoice_number
     *
     * @mbggenerated
     */
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber == null ? null : invoiceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_type
     *
     * @return the value of supplier_invoice.invoice_type
     *
     * @mbggenerated
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_type
     *
     * @param invoiceType the value for supplier_invoice.invoice_type
     *
     * @mbggenerated
     */
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType == null ? null : invoiceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_amount
     *
     * @return the value of supplier_invoice.invoice_amount
     *
     * @mbggenerated
     */
    public Double getInvoiceAmount() {
        return invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_amount
     *
     * @param invoiceAmount the value for supplier_invoice.invoice_amount
     *
     * @mbggenerated
     */
    public void setInvoiceAmount(Double invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoide_date_received
     *
     * @return the value of supplier_invoice.invoide_date_received
     *
     * @mbggenerated
     */
    public Date getInvoideDateReceived() {
        return invoideDateReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoide_date_received
     *
     * @param invoideDateReceived the value for supplier_invoice.invoide_date_received
     *
     * @mbggenerated
     */
    public void setInvoideDateReceived(Date invoideDateReceived) {
        this.invoideDateReceived = invoideDateReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_date_expense
     *
     * @return the value of supplier_invoice.invoice_date_expense
     *
     * @mbggenerated
     */
    public Date getInvoiceDateExpense() {
        return invoiceDateExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_date_expense
     *
     * @param invoiceDateExpense the value for supplier_invoice.invoice_date_expense
     *
     * @mbggenerated
     */
    public void setInvoiceDateExpense(Date invoiceDateExpense) {
        this.invoiceDateExpense = invoiceDateExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_date_expense_start
     *
     * @return the value of supplier_invoice.invoice_date_expense_start
     *
     * @mbggenerated
     */
    public Date getInvoiceDateExpenseStart() {
        return invoiceDateExpenseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_date_expense_start
     *
     * @param invoiceDateExpenseStart the value for supplier_invoice.invoice_date_expense_start
     *
     * @mbggenerated
     */
    public void setInvoiceDateExpenseStart(Date invoiceDateExpenseStart) {
        this.invoiceDateExpenseStart = invoiceDateExpenseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_date_expense_period
     *
     * @return the value of supplier_invoice.invoice_date_expense_period
     *
     * @mbggenerated
     */
    public Date getInvoiceDateExpensePeriod() {
        return invoiceDateExpensePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_date_expense_period
     *
     * @param invoiceDateExpensePeriod the value for supplier_invoice.invoice_date_expense_period
     *
     * @mbggenerated
     */
    public void setInvoiceDateExpensePeriod(Date invoiceDateExpensePeriod) {
        this.invoiceDateExpensePeriod = invoiceDateExpensePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_expense_type
     *
     * @return the value of supplier_invoice.invoice_expense_type
     *
     * @mbggenerated
     */
    public String getInvoiceExpenseType() {
        return invoiceExpenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_expense_type
     *
     * @param invoiceExpenseType the value for supplier_invoice.invoice_expense_type
     *
     * @mbggenerated
     */
    public void setInvoiceExpenseType(String invoiceExpenseType) {
        this.invoiceExpenseType = invoiceExpenseType == null ? null : invoiceExpenseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_fin_location
     *
     * @return the value of supplier_invoice.invoice_fin_location
     *
     * @mbggenerated
     */
    public String getInvoiceFinLocation() {
        return invoiceFinLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_fin_location
     *
     * @param invoiceFinLocation the value for supplier_invoice.invoice_fin_location
     *
     * @mbggenerated
     */
    public void setInvoiceFinLocation(String invoiceFinLocation) {
        this.invoiceFinLocation = invoiceFinLocation == null ? null : invoiceFinLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_fin_currency
     *
     * @return the value of supplier_invoice.invoice_fin_currency
     *
     * @mbggenerated
     */
    public String getInvoiceFinCurrency() {
        return invoiceFinCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_fin_currency
     *
     * @param invoiceFinCurrency the value for supplier_invoice.invoice_fin_currency
     *
     * @mbggenerated
     */
    public void setInvoiceFinCurrency(String invoiceFinCurrency) {
        this.invoiceFinCurrency = invoiceFinCurrency == null ? null : invoiceFinCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_fin_currency_payment
     *
     * @return the value of supplier_invoice.invoice_fin_currency_payment
     *
     * @mbggenerated
     */
    public String getInvoiceFinCurrencyPayment() {
        return invoiceFinCurrencyPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_fin_currency_payment
     *
     * @param invoiceFinCurrencyPayment the value for supplier_invoice.invoice_fin_currency_payment
     *
     * @mbggenerated
     */
    public void setInvoiceFinCurrencyPayment(String invoiceFinCurrencyPayment) {
        this.invoiceFinCurrencyPayment = invoiceFinCurrencyPayment == null ? null : invoiceFinCurrencyPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_1
     *
     * @return the value of supplier_invoice.invoice_basic_1
     *
     * @mbggenerated
     */
    public String getInvoiceBasic1() {
        return invoiceBasic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_1
     *
     * @param invoiceBasic1 the value for supplier_invoice.invoice_basic_1
     *
     * @mbggenerated
     */
    public void setInvoiceBasic1(String invoiceBasic1) {
        this.invoiceBasic1 = invoiceBasic1 == null ? null : invoiceBasic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_2
     *
     * @return the value of supplier_invoice.invoice_basic_2
     *
     * @mbggenerated
     */
    public String getInvoiceBasic2() {
        return invoiceBasic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_2
     *
     * @param invoiceBasic2 the value for supplier_invoice.invoice_basic_2
     *
     * @mbggenerated
     */
    public void setInvoiceBasic2(String invoiceBasic2) {
        this.invoiceBasic2 = invoiceBasic2 == null ? null : invoiceBasic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_3
     *
     * @return the value of supplier_invoice.invoice_basic_3
     *
     * @mbggenerated
     */
    public String getInvoiceBasic3() {
        return invoiceBasic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_3
     *
     * @param invoiceBasic3 the value for supplier_invoice.invoice_basic_3
     *
     * @mbggenerated
     */
    public void setInvoiceBasic3(String invoiceBasic3) {
        this.invoiceBasic3 = invoiceBasic3 == null ? null : invoiceBasic3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_4
     *
     * @return the value of supplier_invoice.invoice_basic_4
     *
     * @mbggenerated
     */
    public String getInvoiceBasic4() {
        return invoiceBasic4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_4
     *
     * @param invoiceBasic4 the value for supplier_invoice.invoice_basic_4
     *
     * @mbggenerated
     */
    public void setInvoiceBasic4(String invoiceBasic4) {
        this.invoiceBasic4 = invoiceBasic4 == null ? null : invoiceBasic4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_5
     *
     * @return the value of supplier_invoice.invoice_basic_5
     *
     * @mbggenerated
     */
    public String getInvoiceBasic5() {
        return invoiceBasic5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_5
     *
     * @param invoiceBasic5 the value for supplier_invoice.invoice_basic_5
     *
     * @mbggenerated
     */
    public void setInvoiceBasic5(String invoiceBasic5) {
        this.invoiceBasic5 = invoiceBasic5 == null ? null : invoiceBasic5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_6
     *
     * @return the value of supplier_invoice.invoice_basic_6
     *
     * @mbggenerated
     */
    public String getInvoiceBasic6() {
        return invoiceBasic6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_6
     *
     * @param invoiceBasic6 the value for supplier_invoice.invoice_basic_6
     *
     * @mbggenerated
     */
    public void setInvoiceBasic6(String invoiceBasic6) {
        this.invoiceBasic6 = invoiceBasic6 == null ? null : invoiceBasic6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_7
     *
     * @return the value of supplier_invoice.invoice_basic_7
     *
     * @mbggenerated
     */
    public String getInvoiceBasic7() {
        return invoiceBasic7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_7
     *
     * @param invoiceBasic7 the value for supplier_invoice.invoice_basic_7
     *
     * @mbggenerated
     */
    public void setInvoiceBasic7(String invoiceBasic7) {
        this.invoiceBasic7 = invoiceBasic7 == null ? null : invoiceBasic7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_8
     *
     * @return the value of supplier_invoice.invoice_basic_8
     *
     * @mbggenerated
     */
    public String getInvoiceBasic8() {
        return invoiceBasic8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_8
     *
     * @param invoiceBasic8 the value for supplier_invoice.invoice_basic_8
     *
     * @mbggenerated
     */
    public void setInvoiceBasic8(String invoiceBasic8) {
        this.invoiceBasic8 = invoiceBasic8 == null ? null : invoiceBasic8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_invoice.invoice_basic_9
     *
     * @return the value of supplier_invoice.invoice_basic_9
     *
     * @mbggenerated
     */
    public String getInvoiceBasic9() {
        return invoiceBasic9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_invoice.invoice_basic_9
     *
     * @param invoiceBasic9 the value for supplier_invoice.invoice_basic_9
     *
     * @mbggenerated
     */
    public void setInvoiceBasic9(String invoiceBasic9) {
        this.invoiceBasic9 = invoiceBasic9 == null ? null : invoiceBasic9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_invoice
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SupplierInvoice other = (SupplierInvoice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSupplierCompany() == null ? other.getSupplierCompany() == null : this.getSupplierCompany().equals(other.getSupplierCompany()))
            && (this.getSupplierSite() == null ? other.getSupplierSite() == null : this.getSupplierSite().equals(other.getSupplierSite()))
            && (this.getSupplierBankCode() == null ? other.getSupplierBankCode() == null : this.getSupplierBankCode().equals(other.getSupplierBankCode()))
            && (this.getSupplierBankName() == null ? other.getSupplierBankName() == null : this.getSupplierBankName().equals(other.getSupplierBankName()))
            && (this.getSupplierExtend1() == null ? other.getSupplierExtend1() == null : this.getSupplierExtend1().equals(other.getSupplierExtend1()))
            && (this.getSupplierExtend2() == null ? other.getSupplierExtend2() == null : this.getSupplierExtend2().equals(other.getSupplierExtend2()))
            && (this.getSupplierExtend3() == null ? other.getSupplierExtend3() == null : this.getSupplierExtend3().equals(other.getSupplierExtend3()))
            && (this.getSupplierExtend4() == null ? other.getSupplierExtend4() == null : this.getSupplierExtend4().equals(other.getSupplierExtend4()))
            && (this.getSupplierExtend5() == null ? other.getSupplierExtend5() == null : this.getSupplierExtend5().equals(other.getSupplierExtend5()))
            && (this.getPoNumber() == null ? other.getPoNumber() == null : this.getPoNumber().equals(other.getPoNumber()))
            && (this.getPoCompany() == null ? other.getPoCompany() == null : this.getPoCompany().equals(other.getPoCompany()))
            && (this.getPoDepartment() == null ? other.getPoDepartment() == null : this.getPoDepartment().equals(other.getPoDepartment()))
            && (this.getPoPrepaymentPoNumber() == null ? other.getPoPrepaymentPoNumber() == null : this.getPoPrepaymentPoNumber().equals(other.getPoPrepaymentPoNumber()))
            && (this.getPoExtend1() == null ? other.getPoExtend1() == null : this.getPoExtend1().equals(other.getPoExtend1()))
            && (this.getPoExtend2() == null ? other.getPoExtend2() == null : this.getPoExtend2().equals(other.getPoExtend2()))
            && (this.getPoExtend3() == null ? other.getPoExtend3() == null : this.getPoExtend3().equals(other.getPoExtend3()))
            && (this.getPoExtend4() == null ? other.getPoExtend4() == null : this.getPoExtend4().equals(other.getPoExtend4()))
            && (this.getPoExtend5() == null ? other.getPoExtend5() == null : this.getPoExtend5().equals(other.getPoExtend5()))
            && (this.getPoExtend6() == null ? other.getPoExtend6() == null : this.getPoExtend6().equals(other.getPoExtend6()))
            && (this.getPoExtend7() == null ? other.getPoExtend7() == null : this.getPoExtend7().equals(other.getPoExtend7()))
            && (this.getPoExtend8() == null ? other.getPoExtend8() == null : this.getPoExtend8().equals(other.getPoExtend8()))
            && (this.getPoExtend9() == null ? other.getPoExtend9() == null : this.getPoExtend9().equals(other.getPoExtend9()))
            && (this.getInvoiceNumber() == null ? other.getInvoiceNumber() == null : this.getInvoiceNumber().equals(other.getInvoiceNumber()))
            && (this.getInvoiceType() == null ? other.getInvoiceType() == null : this.getInvoiceType().equals(other.getInvoiceType()))
            && (this.getInvoiceAmount() == null ? other.getInvoiceAmount() == null : this.getInvoiceAmount().equals(other.getInvoiceAmount()))
            && (this.getInvoideDateReceived() == null ? other.getInvoideDateReceived() == null : this.getInvoideDateReceived().equals(other.getInvoideDateReceived()))
            && (this.getInvoiceDateExpense() == null ? other.getInvoiceDateExpense() == null : this.getInvoiceDateExpense().equals(other.getInvoiceDateExpense()))
            && (this.getInvoiceDateExpenseStart() == null ? other.getInvoiceDateExpenseStart() == null : this.getInvoiceDateExpenseStart().equals(other.getInvoiceDateExpenseStart()))
            && (this.getInvoiceDateExpensePeriod() == null ? other.getInvoiceDateExpensePeriod() == null : this.getInvoiceDateExpensePeriod().equals(other.getInvoiceDateExpensePeriod()))
            && (this.getInvoiceExpenseType() == null ? other.getInvoiceExpenseType() == null : this.getInvoiceExpenseType().equals(other.getInvoiceExpenseType()))
            && (this.getInvoiceFinLocation() == null ? other.getInvoiceFinLocation() == null : this.getInvoiceFinLocation().equals(other.getInvoiceFinLocation()))
            && (this.getInvoiceFinCurrency() == null ? other.getInvoiceFinCurrency() == null : this.getInvoiceFinCurrency().equals(other.getInvoiceFinCurrency()))
            && (this.getInvoiceFinCurrencyPayment() == null ? other.getInvoiceFinCurrencyPayment() == null : this.getInvoiceFinCurrencyPayment().equals(other.getInvoiceFinCurrencyPayment()))
            && (this.getInvoiceBasic1() == null ? other.getInvoiceBasic1() == null : this.getInvoiceBasic1().equals(other.getInvoiceBasic1()))
            && (this.getInvoiceBasic2() == null ? other.getInvoiceBasic2() == null : this.getInvoiceBasic2().equals(other.getInvoiceBasic2()))
            && (this.getInvoiceBasic3() == null ? other.getInvoiceBasic3() == null : this.getInvoiceBasic3().equals(other.getInvoiceBasic3()))
            && (this.getInvoiceBasic4() == null ? other.getInvoiceBasic4() == null : this.getInvoiceBasic4().equals(other.getInvoiceBasic4()))
            && (this.getInvoiceBasic5() == null ? other.getInvoiceBasic5() == null : this.getInvoiceBasic5().equals(other.getInvoiceBasic5()))
            && (this.getInvoiceBasic6() == null ? other.getInvoiceBasic6() == null : this.getInvoiceBasic6().equals(other.getInvoiceBasic6()))
            && (this.getInvoiceBasic7() == null ? other.getInvoiceBasic7() == null : this.getInvoiceBasic7().equals(other.getInvoiceBasic7()))
            && (this.getInvoiceBasic8() == null ? other.getInvoiceBasic8() == null : this.getInvoiceBasic8().equals(other.getInvoiceBasic8()))
            && (this.getInvoiceBasic9() == null ? other.getInvoiceBasic9() == null : this.getInvoiceBasic9().equals(other.getInvoiceBasic9()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_invoice
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSupplierCompany() == null) ? 0 : getSupplierCompany().hashCode());
        result = prime * result + ((getSupplierSite() == null) ? 0 : getSupplierSite().hashCode());
        result = prime * result + ((getSupplierBankCode() == null) ? 0 : getSupplierBankCode().hashCode());
        result = prime * result + ((getSupplierBankName() == null) ? 0 : getSupplierBankName().hashCode());
        result = prime * result + ((getSupplierExtend1() == null) ? 0 : getSupplierExtend1().hashCode());
        result = prime * result + ((getSupplierExtend2() == null) ? 0 : getSupplierExtend2().hashCode());
        result = prime * result + ((getSupplierExtend3() == null) ? 0 : getSupplierExtend3().hashCode());
        result = prime * result + ((getSupplierExtend4() == null) ? 0 : getSupplierExtend4().hashCode());
        result = prime * result + ((getSupplierExtend5() == null) ? 0 : getSupplierExtend5().hashCode());
        result = prime * result + ((getPoNumber() == null) ? 0 : getPoNumber().hashCode());
        result = prime * result + ((getPoCompany() == null) ? 0 : getPoCompany().hashCode());
        result = prime * result + ((getPoDepartment() == null) ? 0 : getPoDepartment().hashCode());
        result = prime * result + ((getPoPrepaymentPoNumber() == null) ? 0 : getPoPrepaymentPoNumber().hashCode());
        result = prime * result + ((getPoExtend1() == null) ? 0 : getPoExtend1().hashCode());
        result = prime * result + ((getPoExtend2() == null) ? 0 : getPoExtend2().hashCode());
        result = prime * result + ((getPoExtend3() == null) ? 0 : getPoExtend3().hashCode());
        result = prime * result + ((getPoExtend4() == null) ? 0 : getPoExtend4().hashCode());
        result = prime * result + ((getPoExtend5() == null) ? 0 : getPoExtend5().hashCode());
        result = prime * result + ((getPoExtend6() == null) ? 0 : getPoExtend6().hashCode());
        result = prime * result + ((getPoExtend7() == null) ? 0 : getPoExtend7().hashCode());
        result = prime * result + ((getPoExtend8() == null) ? 0 : getPoExtend8().hashCode());
        result = prime * result + ((getPoExtend9() == null) ? 0 : getPoExtend9().hashCode());
        result = prime * result + ((getInvoiceNumber() == null) ? 0 : getInvoiceNumber().hashCode());
        result = prime * result + ((getInvoiceType() == null) ? 0 : getInvoiceType().hashCode());
        result = prime * result + ((getInvoiceAmount() == null) ? 0 : getInvoiceAmount().hashCode());
        result = prime * result + ((getInvoideDateReceived() == null) ? 0 : getInvoideDateReceived().hashCode());
        result = prime * result + ((getInvoiceDateExpense() == null) ? 0 : getInvoiceDateExpense().hashCode());
        result = prime * result + ((getInvoiceDateExpenseStart() == null) ? 0 : getInvoiceDateExpenseStart().hashCode());
        result = prime * result + ((getInvoiceDateExpensePeriod() == null) ? 0 : getInvoiceDateExpensePeriod().hashCode());
        result = prime * result + ((getInvoiceExpenseType() == null) ? 0 : getInvoiceExpenseType().hashCode());
        result = prime * result + ((getInvoiceFinLocation() == null) ? 0 : getInvoiceFinLocation().hashCode());
        result = prime * result + ((getInvoiceFinCurrency() == null) ? 0 : getInvoiceFinCurrency().hashCode());
        result = prime * result + ((getInvoiceFinCurrencyPayment() == null) ? 0 : getInvoiceFinCurrencyPayment().hashCode());
        result = prime * result + ((getInvoiceBasic1() == null) ? 0 : getInvoiceBasic1().hashCode());
        result = prime * result + ((getInvoiceBasic2() == null) ? 0 : getInvoiceBasic2().hashCode());
        result = prime * result + ((getInvoiceBasic3() == null) ? 0 : getInvoiceBasic3().hashCode());
        result = prime * result + ((getInvoiceBasic4() == null) ? 0 : getInvoiceBasic4().hashCode());
        result = prime * result + ((getInvoiceBasic5() == null) ? 0 : getInvoiceBasic5().hashCode());
        result = prime * result + ((getInvoiceBasic6() == null) ? 0 : getInvoiceBasic6().hashCode());
        result = prime * result + ((getInvoiceBasic7() == null) ? 0 : getInvoiceBasic7().hashCode());
        result = prime * result + ((getInvoiceBasic8() == null) ? 0 : getInvoiceBasic8().hashCode());
        result = prime * result + ((getInvoiceBasic9() == null) ? 0 : getInvoiceBasic9().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_invoice
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", supplierCompany=").append(supplierCompany);
        sb.append(", supplierSite=").append(supplierSite);
        sb.append(", supplierBankCode=").append(supplierBankCode);
        sb.append(", supplierBankName=").append(supplierBankName);
        sb.append(", supplierExtend1=").append(supplierExtend1);
        sb.append(", supplierExtend2=").append(supplierExtend2);
        sb.append(", supplierExtend3=").append(supplierExtend3);
        sb.append(", supplierExtend4=").append(supplierExtend4);
        sb.append(", supplierExtend5=").append(supplierExtend5);
        sb.append(", poNumber=").append(poNumber);
        sb.append(", poCompany=").append(poCompany);
        sb.append(", poDepartment=").append(poDepartment);
        sb.append(", poPrepaymentPoNumber=").append(poPrepaymentPoNumber);
        sb.append(", poExtend1=").append(poExtend1);
        sb.append(", poExtend2=").append(poExtend2);
        sb.append(", poExtend3=").append(poExtend3);
        sb.append(", poExtend4=").append(poExtend4);
        sb.append(", poExtend5=").append(poExtend5);
        sb.append(", poExtend6=").append(poExtend6);
        sb.append(", poExtend7=").append(poExtend7);
        sb.append(", poExtend8=").append(poExtend8);
        sb.append(", poExtend9=").append(poExtend9);
        sb.append(", invoiceNumber=").append(invoiceNumber);
        sb.append(", invoiceType=").append(invoiceType);
        sb.append(", invoiceAmount=").append(invoiceAmount);
        sb.append(", invoideDateReceived=").append(invoideDateReceived);
        sb.append(", invoiceDateExpense=").append(invoiceDateExpense);
        sb.append(", invoiceDateExpenseStart=").append(invoiceDateExpenseStart);
        sb.append(", invoiceDateExpensePeriod=").append(invoiceDateExpensePeriod);
        sb.append(", invoiceExpenseType=").append(invoiceExpenseType);
        sb.append(", invoiceFinLocation=").append(invoiceFinLocation);
        sb.append(", invoiceFinCurrency=").append(invoiceFinCurrency);
        sb.append(", invoiceFinCurrencyPayment=").append(invoiceFinCurrencyPayment);
        sb.append(", invoiceBasic1=").append(invoiceBasic1);
        sb.append(", invoiceBasic2=").append(invoiceBasic2);
        sb.append(", invoiceBasic3=").append(invoiceBasic3);
        sb.append(", invoiceBasic4=").append(invoiceBasic4);
        sb.append(", invoiceBasic5=").append(invoiceBasic5);
        sb.append(", invoiceBasic6=").append(invoiceBasic6);
        sb.append(", invoiceBasic7=").append(invoiceBasic7);
        sb.append(", invoiceBasic8=").append(invoiceBasic8);
        sb.append(", invoiceBasic9=").append(invoiceBasic9);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}