package com.liquid.apw.demo.batch.orm.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.liquid.apw.demo.batch.beans.InvoiceCertification;
import com.liquid.apw.demo.batch.orm.vo.InvoiceCertificationVO;

@Mapper
public interface InvoiceCertificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apw_invoice_certification
     *
     * @mbggenerated
     */
    @Delete({
        "delete from apw_invoice_certification",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apw_invoice_certification
     *
     * @mbggenerated
     */
    @Insert({
        "insert into apw_invoice_certification (id, supplier_company, ",
        "supplier_site, supplier_bank_code, ",
        "supplier_bank_name, supplier_extend_1, ",
        "supplier_extend_2, supplier_extend_3, ",
        "supplier_extend_4, supplier_extend_5, ",
        "po_number, po_company, ",
        "po_department, po_prepayment_po_number, ",
        "po_extend_1, po_extend_2, ",
        "po_extend_3, po_extend_4, ",
        "po_extend_5, po_extend_6, ",
        "po_extend_7, po_extend_8, ",
        "po_extend_9, invoice_number, ",
        "invoice_type, invoice_amount, ",
        "invoide_date_received, invoice_date_expense, ",
        "invoice_date_expense_start, invoice_date_expense_period, ",
        "invoice_expense_type, invoice_fin_location, ",
        "invoice_fin_currency, invoice_fin_currency_payment, ",
        "invoice_basic_1, invoice_basic_2, ",
        "invoice_basic_3, invoice_basic_4, ",
        "invoice_basic_5, invoice_basic_6, ",
        "invoice_basic_7, invoice_basic_8, ",
        "invoice_basic_9, tax_code, ",
        "tax_place, tax_party, ",
        "tax_product, tax_process, ",
        "tax_amount)",
        "values (#{id,jdbcType=INTEGER}, #{supplierCompany,jdbcType=VARCHAR}, ",
        "#{supplierSite,jdbcType=VARCHAR}, #{supplierBankCode,jdbcType=VARCHAR}, ",
        "#{supplierBankName,jdbcType=VARCHAR}, #{supplierExtend1,jdbcType=VARCHAR}, ",
        "#{supplierExtend2,jdbcType=VARCHAR}, #{supplierExtend3,jdbcType=VARCHAR}, ",
        "#{supplierExtend4,jdbcType=VARCHAR}, #{supplierExtend5,jdbcType=VARCHAR}, ",
        "#{poNumber,jdbcType=VARCHAR}, #{poCompany,jdbcType=VARCHAR}, ",
        "#{poDepartment,jdbcType=VARCHAR}, #{poPrepaymentPoNumber,jdbcType=VARCHAR}, ",
        "#{poExtend1,jdbcType=VARCHAR}, #{poExtend2,jdbcType=VARCHAR}, ",
        "#{poExtend3,jdbcType=VARCHAR}, #{poExtend4,jdbcType=VARCHAR}, ",
        "#{poExtend5,jdbcType=VARCHAR}, #{poExtend6,jdbcType=VARCHAR}, ",
        "#{poExtend7,jdbcType=VARCHAR}, #{poExtend8,jdbcType=VARCHAR}, ",
        "#{poExtend9,jdbcType=VARCHAR}, #{invoiceNumber,jdbcType=VARCHAR}, ",
        "#{invoiceType,jdbcType=VARCHAR}, #{invoiceAmount,jdbcType=DOUBLE}, ",
        "#{invoideDateReceived,jdbcType=DATE}, #{invoiceDateExpense,jdbcType=DATE}, ",
        "#{invoiceDateExpenseStart,jdbcType=DATE}, #{invoiceDateExpensePeriod,jdbcType=DATE}, ",
        "#{invoiceExpenseType,jdbcType=VARCHAR}, #{invoiceFinLocation,jdbcType=VARCHAR}, ",
        "#{invoiceFinCurrency,jdbcType=VARCHAR}, #{invoiceFinCurrencyPayment,jdbcType=VARCHAR}, ",
        "#{invoiceBasic1,jdbcType=VARCHAR}, #{invoiceBasic2,jdbcType=VARCHAR}, ",
        "#{invoiceBasic3,jdbcType=VARCHAR}, #{invoiceBasic4,jdbcType=VARCHAR}, ",
        "#{invoiceBasic5,jdbcType=VARCHAR}, #{invoiceBasic6,jdbcType=VARCHAR}, ",
        "#{invoiceBasic7,jdbcType=VARCHAR}, #{invoiceBasic8,jdbcType=VARCHAR}, ",
        "#{invoiceBasic9,jdbcType=VARCHAR}, #{taxCode,jdbcType=VARCHAR}, ",
        "#{taxPlace,jdbcType=VARCHAR}, #{taxParty,jdbcType=VARCHAR}, ",
        "#{taxProduct,jdbcType=VARCHAR}, #{taxProcess,jdbcType=VARCHAR}, ",
        "#{taxAmount,jdbcType=VARCHAR})"
    })
    int insert(InvoiceCertification record);

    /**
     * 批量插入数据
     * @param list
     * @return
     */
    @Insert({
    	"<script>",
        "insert into apw_invoice_certification (id, supplier_company, ",
        "supplier_site, supplier_bank_code, ",
        "supplier_bank_name, supplier_extend_1, ",
        "supplier_extend_2, supplier_extend_3, ",
        "supplier_extend_4, supplier_extend_5, ",
        "po_number, po_company, ",
        "po_department, po_prepayment_po_number, ",
        "po_extend_1, po_extend_2, ",
        "po_extend_3, po_extend_4, ",
        "po_extend_5, po_extend_6, ",
        "po_extend_7, po_extend_8, ",
        "po_extend_9, invoice_number, ",
        "invoice_type, invoice_amount, ",
        "invoide_date_received, invoice_date_expense, ",
        "invoice_date_expense_start, invoice_date_expense_period, ",
        "invoice_expense_type, invoice_fin_location, ",
        "invoice_fin_currency, invoice_fin_currency_payment, ",
        "invoice_basic_1, invoice_basic_2, ",
        "invoice_basic_3, invoice_basic_4, ",
        "invoice_basic_5, invoice_basic_6, ",
        "invoice_basic_7, invoice_basic_8, ",
        "invoice_basic_9, tax_code, ",
        "tax_place, tax_party, ",
        "tax_product, tax_process, ",
        "tax_amount)",
        "values",
        "<foreach collection=\"list\" item=\"certif\" index=\"index\" separator=\",\" > ",
        "(#{certif.id,jdbcType=INTEGER}, #{certif.supplierCompany,jdbcType=VARCHAR}, ",
        "#{certif.supplierSite,jdbcType=VARCHAR}, #{certif.supplierBankCode,jdbcType=VARCHAR}, ",
        "#{certif.supplierBankName,jdbcType=VARCHAR}, #{certif.supplierExtend1,jdbcType=VARCHAR}, ",
        "#{certif.supplierExtend2,jdbcType=VARCHAR}, #{certif.supplierExtend3,jdbcType=VARCHAR}, ",
        "#{certif.supplierExtend4,jdbcType=VARCHAR}, #{certif.supplierExtend5,jdbcType=VARCHAR}, ",
        "#{certif.poNumber,jdbcType=VARCHAR}, #{certif.poCompany,jdbcType=VARCHAR}, ",
        "#{certif.poDepartment,jdbcType=VARCHAR}, #{certif.poPrepaymentPoNumber,jdbcType=VARCHAR}, ",
        "#{certif.poExtend1,jdbcType=VARCHAR}, #{certif.poExtend2,jdbcType=VARCHAR}, ",
        "#{certif.poExtend3,jdbcType=VARCHAR}, #{certif.poExtend4,jdbcType=VARCHAR}, ",
        "#{certif.poExtend5,jdbcType=VARCHAR}, #{certif.poExtend6,jdbcType=VARCHAR}, ",
        "#{certif.poExtend7,jdbcType=VARCHAR}, #{certif.poExtend8,jdbcType=VARCHAR}, ",
        "#{certif.poExtend9,jdbcType=VARCHAR}, #{certif.invoiceNumber,jdbcType=VARCHAR}, ",
        "#{certif.invoiceType,jdbcType=VARCHAR}, #{certif.invoiceAmount,jdbcType=DOUBLE}, ",
        "#{certif.invoideDateReceived,jdbcType=DATE}, #{certif.invoiceDateExpense,jdbcType=DATE}, ",
        "#{certif.invoiceDateExpenseStart,jdbcType=DATE}, #{certif.invoiceDateExpensePeriod,jdbcType=DATE}, ",
        "#{certif.invoiceExpenseType,jdbcType=VARCHAR}, #{certif.invoiceFinLocation,jdbcType=VARCHAR}, ",
        "#{certif.invoiceFinCurrency,jdbcType=VARCHAR}, #{certif.invoiceFinCurrencyPayment,jdbcType=VARCHAR}, ",
        "#{certif.invoiceBasic1,jdbcType=VARCHAR}, #{certif.invoiceBasic2,jdbcType=VARCHAR}, ",
        "#{certif.invoiceBasic3,jdbcType=VARCHAR}, #{certif.invoiceBasic4,jdbcType=VARCHAR}, ",
        "#{certif.invoiceBasic5,jdbcType=VARCHAR}, #{certif.invoiceBasic6,jdbcType=VARCHAR}, ",
        "#{certif.invoiceBasic7,jdbcType=VARCHAR}, #{certif.invoiceBasic8,jdbcType=VARCHAR}, ",
        "#{certif.invoiceBasic9,jdbcType=VARCHAR}, #{certif.taxCode,jdbcType=VARCHAR}, ",
        "#{certif.taxPlace,jdbcType=VARCHAR}, #{certif.taxParty,jdbcType=VARCHAR}, ",
        "#{certif.taxProduct,jdbcType=VARCHAR}, #{certif.taxProcess,jdbcType=VARCHAR}, ",
        "#{certif.taxAmount,jdbcType=VARCHAR})",
        "</foreach> </script>"
    })
    int insertList(List<InvoiceCertification> list);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apw_invoice_certification
     *
     * @mbggenerated
     */
    @InsertProvider(type=InvoiceCertificationSqlProvider.class, method="insertSelective")
    int insertSelective(InvoiceCertification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apw_invoice_certification
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, supplier_company, supplier_site, supplier_bank_code, supplier_bank_name, ",
        "supplier_extend_1, supplier_extend_2, supplier_extend_3, supplier_extend_4, ",
        "supplier_extend_5, po_number, po_company, po_department, po_prepayment_po_number, ",
        "po_extend_1, po_extend_2, po_extend_3, po_extend_4, po_extend_5, po_extend_6, ",
        "po_extend_7, po_extend_8, po_extend_9, invoice_number, invoice_type, invoice_amount, ",
        "invoide_date_received, invoice_date_expense, invoice_date_expense_start, invoice_date_expense_period, ",
        "invoice_expense_type, invoice_fin_location, invoice_fin_currency, invoice_fin_currency_payment, ",
        "invoice_basic_1, invoice_basic_2, invoice_basic_3, invoice_basic_4, invoice_basic_5, ",
        "invoice_basic_6, invoice_basic_7, invoice_basic_8, invoice_basic_9, tax_code, ",
        "tax_place, tax_party, tax_product, tax_process, tax_amount",
        "from apw_invoice_certification",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="supplier_company", property="supplierCompany", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_site", property="supplierSite", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_bank_code", property="supplierBankCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_bank_name", property="supplierBankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_1", property="supplierExtend1", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_2", property="supplierExtend2", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_3", property="supplierExtend3", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_4", property="supplierExtend4", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_5", property="supplierExtend5", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_number", property="poNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_company", property="poCompany", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_department", property="poDepartment", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_prepayment_po_number", property="poPrepaymentPoNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_1", property="poExtend1", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_2", property="poExtend2", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_3", property="poExtend3", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_4", property="poExtend4", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_5", property="poExtend5", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_6", property="poExtend6", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_7", property="poExtend7", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_8", property="poExtend8", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_9", property="poExtend9", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_number", property="invoiceNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_type", property="invoiceType", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_amount", property="invoiceAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="invoide_date_received", property="invoideDateReceived", jdbcType=JdbcType.DATE),
        @Result(column="invoice_date_expense", property="invoiceDateExpense", jdbcType=JdbcType.DATE),
        @Result(column="invoice_date_expense_start", property="invoiceDateExpenseStart", jdbcType=JdbcType.DATE),
        @Result(column="invoice_date_expense_period", property="invoiceDateExpensePeriod", jdbcType=JdbcType.DATE),
        @Result(column="invoice_expense_type", property="invoiceExpenseType", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_fin_location", property="invoiceFinLocation", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_fin_currency", property="invoiceFinCurrency", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_fin_currency_payment", property="invoiceFinCurrencyPayment", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_1", property="invoiceBasic1", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_2", property="invoiceBasic2", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_3", property="invoiceBasic3", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_4", property="invoiceBasic4", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_5", property="invoiceBasic5", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_6", property="invoiceBasic6", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_7", property="invoiceBasic7", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_8", property="invoiceBasic8", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_9", property="invoiceBasic9", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_code", property="taxCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_place", property="taxPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_party", property="taxParty", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_product", property="taxProduct", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_process", property="taxProcess", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_amount", property="taxAmount", jdbcType=JdbcType.VARCHAR)
    })
    InvoiceCertification selectByPrimaryKey(Integer id);
    
    /**
     * 条件查询
     * @param id
     * @return
     */
    @Select({
    	"<script>",
        "select",
        "id, supplier_company, supplier_site, supplier_bank_code, supplier_bank_name, ",
        "supplier_extend_1, supplier_extend_2, supplier_extend_3, supplier_extend_4, ",
        "supplier_extend_5, po_number, po_company, po_department, po_prepayment_po_number, ",
        "po_extend_1, po_extend_2, po_extend_3, po_extend_4, po_extend_5, po_extend_6, ",
        "po_extend_7, po_extend_8, po_extend_9, invoice_number, invoice_type, invoice_amount, ",
        "invoide_date_received, invoice_date_expense, invoice_date_expense_start, invoice_date_expense_period, ",
        "invoice_expense_type, invoice_fin_location, invoice_fin_currency, invoice_fin_currency_payment, ",
        "invoice_basic_1, invoice_basic_2, invoice_basic_3, invoice_basic_4, invoice_basic_5, ",
        "invoice_basic_6, invoice_basic_7, invoice_basic_8, invoice_basic_9, tax_code, ",
        "tax_place, tax_party, tax_product, tax_process, tax_amount",
        "from apw_invoice_certification",
        "where 1=1 ",
        "<if test=\"id != null\"> and id = #{id,jdbcType=INTEGER} </if>",
        "<if test=\"orderType == 'desc'\"> order by id desc </if>",
        "<if test=\"_pagesize != null\"> limit 0, #{_pagesize} </if>",
        "</script>"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="supplier_company", property="supplierCompany", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_site", property="supplierSite", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_bank_code", property="supplierBankCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_bank_name", property="supplierBankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_1", property="supplierExtend1", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_2", property="supplierExtend2", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_3", property="supplierExtend3", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_4", property="supplierExtend4", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_extend_5", property="supplierExtend5", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_number", property="poNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_company", property="poCompany", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_department", property="poDepartment", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_prepayment_po_number", property="poPrepaymentPoNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_1", property="poExtend1", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_2", property="poExtend2", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_3", property="poExtend3", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_4", property="poExtend4", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_5", property="poExtend5", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_6", property="poExtend6", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_7", property="poExtend7", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_8", property="poExtend8", jdbcType=JdbcType.VARCHAR),
        @Result(column="po_extend_9", property="poExtend9", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_number", property="invoiceNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_type", property="invoiceType", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_amount", property="invoiceAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="invoide_date_received", property="invoideDateReceived", jdbcType=JdbcType.DATE),
        @Result(column="invoice_date_expense", property="invoiceDateExpense", jdbcType=JdbcType.DATE),
        @Result(column="invoice_date_expense_start", property="invoiceDateExpenseStart", jdbcType=JdbcType.DATE),
        @Result(column="invoice_date_expense_period", property="invoiceDateExpensePeriod", jdbcType=JdbcType.DATE),
        @Result(column="invoice_expense_type", property="invoiceExpenseType", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_fin_location", property="invoiceFinLocation", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_fin_currency", property="invoiceFinCurrency", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_fin_currency_payment", property="invoiceFinCurrencyPayment", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_1", property="invoiceBasic1", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_2", property="invoiceBasic2", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_3", property="invoiceBasic3", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_4", property="invoiceBasic4", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_5", property="invoiceBasic5", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_6", property="invoiceBasic6", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_7", property="invoiceBasic7", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_8", property="invoiceBasic8", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoice_basic_9", property="invoiceBasic9", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_code", property="taxCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_place", property="taxPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_party", property="taxParty", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_product", property="taxProduct", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_process", property="taxProcess", jdbcType=JdbcType.VARCHAR),
        @Result(column="tax_amount", property="taxAmount", jdbcType=JdbcType.VARCHAR)
    })
    List<InvoiceCertification> selectByCondition(InvoiceCertificationVO certif);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apw_invoice_certification
     *
     * @mbggenerated
     */
    @UpdateProvider(type=InvoiceCertificationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InvoiceCertification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apw_invoice_certification
     *
     * @mbggenerated
     */
    @Update({
        "update apw_invoice_certification",
        "set supplier_company = #{supplierCompany,jdbcType=VARCHAR},",
          "supplier_site = #{supplierSite,jdbcType=VARCHAR},",
          "supplier_bank_code = #{supplierBankCode,jdbcType=VARCHAR},",
          "supplier_bank_name = #{supplierBankName,jdbcType=VARCHAR},",
          "supplier_extend_1 = #{supplierExtend1,jdbcType=VARCHAR},",
          "supplier_extend_2 = #{supplierExtend2,jdbcType=VARCHAR},",
          "supplier_extend_3 = #{supplierExtend3,jdbcType=VARCHAR},",
          "supplier_extend_4 = #{supplierExtend4,jdbcType=VARCHAR},",
          "supplier_extend_5 = #{supplierExtend5,jdbcType=VARCHAR},",
          "po_number = #{poNumber,jdbcType=VARCHAR},",
          "po_company = #{poCompany,jdbcType=VARCHAR},",
          "po_department = #{poDepartment,jdbcType=VARCHAR},",
          "po_prepayment_po_number = #{poPrepaymentPoNumber,jdbcType=VARCHAR},",
          "po_extend_1 = #{poExtend1,jdbcType=VARCHAR},",
          "po_extend_2 = #{poExtend2,jdbcType=VARCHAR},",
          "po_extend_3 = #{poExtend3,jdbcType=VARCHAR},",
          "po_extend_4 = #{poExtend4,jdbcType=VARCHAR},",
          "po_extend_5 = #{poExtend5,jdbcType=VARCHAR},",
          "po_extend_6 = #{poExtend6,jdbcType=VARCHAR},",
          "po_extend_7 = #{poExtend7,jdbcType=VARCHAR},",
          "po_extend_8 = #{poExtend8,jdbcType=VARCHAR},",
          "po_extend_9 = #{poExtend9,jdbcType=VARCHAR},",
          "invoice_number = #{invoiceNumber,jdbcType=VARCHAR},",
          "invoice_type = #{invoiceType,jdbcType=VARCHAR},",
          "invoice_amount = #{invoiceAmount,jdbcType=DOUBLE},",
          "invoide_date_received = #{invoideDateReceived,jdbcType=DATE},",
          "invoice_date_expense = #{invoiceDateExpense,jdbcType=DATE},",
          "invoice_date_expense_start = #{invoiceDateExpenseStart,jdbcType=DATE},",
          "invoice_date_expense_period = #{invoiceDateExpensePeriod,jdbcType=DATE},",
          "invoice_expense_type = #{invoiceExpenseType,jdbcType=VARCHAR},",
          "invoice_fin_location = #{invoiceFinLocation,jdbcType=VARCHAR},",
          "invoice_fin_currency = #{invoiceFinCurrency,jdbcType=VARCHAR},",
          "invoice_fin_currency_payment = #{invoiceFinCurrencyPayment,jdbcType=VARCHAR},",
          "invoice_basic_1 = #{invoiceBasic1,jdbcType=VARCHAR},",
          "invoice_basic_2 = #{invoiceBasic2,jdbcType=VARCHAR},",
          "invoice_basic_3 = #{invoiceBasic3,jdbcType=VARCHAR},",
          "invoice_basic_4 = #{invoiceBasic4,jdbcType=VARCHAR},",
          "invoice_basic_5 = #{invoiceBasic5,jdbcType=VARCHAR},",
          "invoice_basic_6 = #{invoiceBasic6,jdbcType=VARCHAR},",
          "invoice_basic_7 = #{invoiceBasic7,jdbcType=VARCHAR},",
          "invoice_basic_8 = #{invoiceBasic8,jdbcType=VARCHAR},",
          "invoice_basic_9 = #{invoiceBasic9,jdbcType=VARCHAR},",
          "tax_code = #{taxCode,jdbcType=VARCHAR},",
          "tax_place = #{taxPlace,jdbcType=VARCHAR},",
          "tax_party = #{taxParty,jdbcType=VARCHAR},",
          "tax_product = #{taxProduct,jdbcType=VARCHAR},",
          "tax_process = #{taxProcess,jdbcType=VARCHAR},",
          "tax_amount = #{taxAmount,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(InvoiceCertification record);
}